name: CI
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  flutter_test_on_win_srv2019:
    name: 'Run flutter tests and analizes on Windows Server 2019'
    runs-on: windows-2019 # windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          # The Flutter version to make available on the path
          # flutter-version: # optional
          # The Flutter build release channel
          channel: 'stable' # optional, default is 
          cache: false # optional
          cache-key: flutter # optional, default is flutter
          cache-path: ${{ runner.tool_cache }}/flutter # optional, default is ${{ runner.tool_cache }}/flutter
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
  
  build:
    name: "Build flutter app on Windows Server 2019"
    runs-on: windows-2019 # windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Flutter
        uses: subosito/flutter-action@v2.3.0
        with:
          # The Flutter version to make available on the path
          # flutter-version: # optional
          # The Flutter build release channel
          channel: 'stable' # optional, default is 
      - run: flutter --version
      - run: flutter pub get
      - run: flutter test
      - run: flutter config --enable-windows-desktop
      - run: flutter build windows
